name: Cloud Defense DockerImageScan
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: |
          docker build -t foo/foobar .
      - name: List images
        run: |
          docker images
      - name: Run Application
        run: |
          docker-compose up -d
          docker-compose ps
      - name: Install Cloud Defense
        run: |
          curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz
          tar -C /tmp -xzf /tmp/cd-latest-linux-x64.tar.gz
          chmod +x /tmp/cdefense
      - name: Run DAST Scan
        run: |
          curl http://localhost:1337
          /tmp/cdefense dast --api-key=d6d2431d-5c13-b100-7420-4890ce39c191 --url="http://172.17.0.1:1337" --project-name="foo/foobar"
      - name: Run Container Scan
        run: /tmp/cdefense container --api-key=d6d2431d-5c13-b100-7420-4890ce39c191 --image-name="foo/foobar" --project-name="foo/foobar"
